version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

  consumer:
    build: ./consumer
    volumes:
      - ./consumer:/usr/src/app
    ports:
      - "8001:8081"

  publisher:
    build: ./publisher
    volumes:
      - ./publisher:/usr/src/app
    ports:
      - "8002:8082"